version: '3.5'
services:
  api01:
    image: luizvellozo/rinha-vertx:latest
    hostname: api01
    depends_on:
      - db
    expose:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.9GB'
    environment:
      DB_USER: root
      DB_PASS: 1234
      DB: rinhadb
      DB_HOST: db
      DB_PORT: 5432
      POOL_SIZE: 20
      JAVA_OPTS: "-verbose:gc -Xmx768M -Xms768M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:+ExitOnOutOfMemoryError"

  api02:
    image: luizvellozo/rinha-vertx:latest
    hostname: api02
    depends_on:
      - db
    expose:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.9GB'
    environment:
      DB_USER: root
      DB_PASS: 1234
      DB: rinhadb
      DB_HOST: db
      DB_PORT: 5432
      POOL_SIZE: 20
      JAVA_OPTS: "-verbose:gc -Xmx768M -Xms768M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:+ExitOnOutOfMemoryError"

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rinhadb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '1.4'
          memory: '1.0GB'

networks:
  default:
    driver: bridge
    name: rinha
